# This is a basic workflow to help you get started with Actions

name: Cerberus Checks

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a CPD check
        run: java -jar cerberus-4.0.jar CPD --files=./src --format=text --language=java --minimum-tokens=30
      
      - name: Run a FPM check
        run: java -jar cerberus-4.0.jar FPM --files=./src --java-version=8 --language=java --rulesets=category/java/bestpractices.xml
    
      - name: Run SWD check
        run: java -jar cerberus-4.0.jar SWD --files=./src --language=java
